// packages/solid/src/types/primitives.ts
import type { JSX } from 'solid-js'

export type UnknownProps = Record<string, unknown>
export type VariantKey = string
export type ResolvedProps = Readonly<UnknownProps>
export type { FilterPredicate } from '@polymorphic-ui/adapter-utils'
export type SolidElement = JSX.Element
export type SlotRenderFn = (props: UnknownProps) => SolidElement

// packages/react/src/shared/types/primitives.ts
import type { ComponentType, ReactElement } from 'react'

export type UnknownProps = Record<string, unknown>
export type SlotComponent = ComponentType<UnknownProps>
export type VariantKey = string
export type ResolvedProps = Readonly<UnknownProps>
export type { FilterPredicate } from '@polymorphic-ui/adapter-utils'
export type NormalizeChildren = (children: unknown) => ReactElement[]
