// adapters/react/src/legacy/create-contract-component.ts
import type {
  AnyClassPluginFactory,
  AnyRecord,
  ContractAllowedOf,
  ContractPluginOf,
  ContractPresetOf,
  ContractPropsOf,
  ContractTagOf,
  ContractVariantsOf,
  ElementForTag,
  ElementType,
  EmptyRecord,
  ExtractPluginProps,
  MergeRecords,
  PolymorphicGenerics,
  RecipeMap,
  VariantMap,
} from '@praxis-kit/core'
import { finalizeComponent, invariant } from '@praxis-kit/adapter-utils'
import type { ReactElement, Ref } from 'react'
import { forwardRef, useCallback, useRef } from 'react'
import type { PolymorphicComponent, ReactFactoryOptions, UnknownProps } from '../shared'
import { applyDisplayName, isReactFactoryOptions, mergeRefs, render } from '../shared'
import { buildRuntime } from './build-runtime'

/**
 * Creates a polymorphic React component with praxis-kit contracts applied, for React 18 and
 * earlier (use `praxis-kit/react` instead on React 19, which accepts `ref` as a plain prop).
 *
 * ```tsx
 * const Button = createContractComponent({
 *   tag: 'button',
 *   name: 'Button',
 *   styling: {
 *     base: 'btn',
 *     variants: { intent: { primary: 'btn--primary', ghost: 'btn--ghost' } },
 *     defaults: { intent: 'primary' },
 *   },
 * })
 *
 * <Button intent="ghost" as="a" href="/home">Home</Button>
 * ```
 *
 * Returns a `forwardRef` component — `ref` is forwarded to the rendered host element the same
 * way it works in `praxis-kit/react`. Pass `subComponents` to attach named sub-components
 * (`Card.Header`) and `onElement` to run setup once the real DOM element exists.
 *
 * `TDefault`/`Props`/`Variants`/`TPreset`/`TPlugin`/`TAllowed` are each `ContractXOf<C>`-derived
 * *defaults* on this function's own type parameter list, mirroring `current/create-contract-component.ts`
 * exactly — see that file's own doc comment for why (computed as function type-parameter defaults,
 * not inline body computations, which doesn't resolve for a still-abstract `C`).
 */
export function createContractComponent<
  C extends ReactFactoryOptions,
  TDefault extends ElementType = ContractTagOf<C>,
  Props extends UnknownProps = ContractPropsOf<C>,
  Variants extends Readonly<VariantMap> = ContractVariantsOf<C>,
  TPreset extends RecipeMap<VariantMap> = ContractPresetOf<C>,
  TPlugin extends AnyClassPluginFactory = ContractPluginOf<C>,
  TAllowed extends ElementType = ContractAllowedOf<C>,
  TSubComponents extends Readonly<AnyRecord> = EmptyRecord,
>(
  options: C & {
    readonly subComponents?: TSubComponents
  },
): MergeRecords<
  PolymorphicComponent<
    PolymorphicGenerics<
      TDefault,
      MergeRecords<Props, ExtractPluginProps<TPlugin>>,
      Variants,
      TPreset,
      TAllowed
    >,
    C
  >,
  TSubComponents
> {
  // Confirmed pre-existing gap (found while migrating `current` through this same refactor):
  // this check was missing here even before this signature collapse. Added to match `current`,
  // not required by the refactor itself, but low-risk and worth closing alongside.
  invariant(isReactFactoryOptions(options), 'options is not a valid ReactFactoryOptions object')
  /**
   * `C` and `TDefault`/`Props`/`Variants`/`TPreset`/`TAllowed` are formally independent type
   * parameters to the checker — see `current/create-contract-component.ts`'s identical comment
   * for the full explanation. The `invariant` above is what actually guarantees `options` is
   * `ReactFactoryOptions` shaped; this assertion bridges the gap in the compiler's reasoning.
   */
  const bundle = buildRuntime(
    options as unknown as ReactFactoryOptions<
      TDefault,
      Props,
      Variants,
      TPreset,
      AnyClassPluginFactory,
      TAllowed
    >,
  )
  const { onElement } = options

  // React 18: ref is not available as a plain prop — forwardRef is required.
  const Component = forwardRef<unknown, UnknownProps>(function Component(
    props: UnknownProps,
    ref: Ref<unknown> | null,
  ): ReactElement {
    // Keep current on every render so the stable callback ref can always read the latest
    // props via getProps() without re-registering.
    const propsRef = useRef(props)
    propsRef.current = props
    const cleanupRef = useRef<(() => void) | undefined>(undefined)

    // `onElement` originates from the options object closed over by createContractComponent,
    // not from props, so it's static for the component's lifetime — this callback intentionally
    // stays stable across renders. React only re-invokes a stable callback ref when the
    // underlying element instance changes (mount, replacement, or unmount), so onElement is
    // registered once for each mounted element, regardless of how many times Component re-renders.
    const onElementRef = useCallback((el: Element | null) => {
      if (!onElement) return
      if (el) {
        // Defensive: React currently always calls this ref with `null` before a replacement
        // element, but that ordering isn't part of the formal callback-ref contract — clean up
        // any existing registration first so a hypothetical el→el invocation can't leak one.
        // Cleared right after invoking, not left to be overwritten below, so a subsequent
        // `onElement(...)` throw doesn't leave a stale, already-invoked cleanup in place to be
        // run a second time on unmount. (Mirrors `current/create-contract-component.ts`.)
        cleanupRef.current?.()
        cleanupRef.current = undefined
        // The real element's actual tag is only known at runtime (`tag` default or a consumer's
        // `as` override); `onElement`'s parameter type narrows that per-component via `TDefault`/
        // `TAllowed`, which the DOM ref API itself can't express — see `FactoryOptions.onElement`.
        cleanupRef.current =
          onElement(
            el as ElementForTag<TDefault | TAllowed>,
            () => propsRef.current as unknown as Readonly<Props>,
          ) ?? undefined
      } else {
        cleanupRef.current?.()
        cleanupRef.current = undefined
      }
    }, [])

    const mergedRef = onElement ? mergeRefs(ref, onElementRef) : ref
    return render({ ...bundle, props, ref: mergedRef })
  })

  applyDisplayName(Component, options.name)
  const assembled = finalizeComponent(
    Component,
    bundle.runtime.options.defaultTag,
    options.subComponents,
  )

  type G = PolymorphicGenerics<
    TDefault,
    MergeRecords<Props, ExtractPluginProps<TPlugin>>,
    Variants,
    TPreset,
    TAllowed
  >

  return assembled as unknown as MergeRecords<PolymorphicComponent<G, C>, TSubComponents>
}

// adapters/solid/src/create-contract-component.ts
import type {
  AnyClassPluginFactory,
  AnyRecord,
  ContractPluginOf,
  ContractPresetOf,
  ContractPropsOf,
  ContractTagOf,
  ContractVariantsOf,
  ElementType,
  EmptyRecord,
  ExtractPluginProps,
  MergeRecords,
  PolymorphicGenerics,
  RecipeMap,
  VariantMap,
} from '@praxis-kit/core'
import { finalizeComponent, invariant } from '@praxis-kit/adapter-utils'
import { mergeProps, onCleanup } from 'solid-js'
import { applyDisplayName } from './apply-display-name'
import { buildRuntime } from './build-runtime'
import { isPolymorphicComponent } from './is-polymorphic-component'
import { render } from './render'
import { isSolidFactoryOptions } from './to-solid-factory-options'
import type { SolidFactoryOptions } from './solid-options'
import type { KnownProps, PolymorphicComponent, SolidElement, UnknownProps } from './types'

/**
 * Creates a polymorphic Solid component with praxis-kit contracts applied.
 *
 * ```tsx
 * const Button = createContractComponent({
 *   tag: 'button',
 *   name: 'Button',
 *   styling: {
 *     base: 'btn',
 *     variants: { intent: { primary: 'btn--primary', ghost: 'btn--ghost' } },
 *     defaults: { intent: 'primary' },
 *   },
 * })
 *
 * <Button intent="ghost" as="a" href="/home">Home</Button>
 * ```
 *
 * `ref` is forwarded as an ordinary Solid ref callback. Pass `subComponents` to attach named
 * sub-components (`Card.Header`) and `onElement` to run setup once the real DOM element exists.
 *
 * `TDefault`/`Props`/`Variants`/`TPreset`/`TPlugin` are each `ContractXOf<C>`-derived *defaults*
 * on this function's own type parameter list, mirroring `@praxis-kit/react`'s identical fix — see
 * that adapter's own doc comment for why (computed as function type-parameter defaults, not inline
 * body computations, which doesn't resolve for a still-abstract `C`). No `TAllowed` here, matching
 * this adapter's pre-refactor behavior — Solid never threaded it as its own generic.
 */
export function createContractComponent<
  C extends SolidFactoryOptions,
  TDefault extends ElementType = ContractTagOf<C>,
  Props extends UnknownProps = ContractPropsOf<C>,
  Variants extends Readonly<VariantMap> = ContractVariantsOf<C>,
  TPreset extends RecipeMap<VariantMap> = ContractPresetOf<C>,
  TPlugin extends AnyClassPluginFactory = ContractPluginOf<C>,
  TSubComponents extends Readonly<AnyRecord> = EmptyRecord,
>(
  options: C & {
    readonly subComponents?: TSubComponents
  },
): MergeRecords<
  PolymorphicComponent<
    PolymorphicGenerics<
      TDefault,
      MergeRecords<Props, ExtractPluginProps<TPlugin>>,
      Variants,
      TPreset
    >,
    C
  >,
  TSubComponents
> {
  invariant(isSolidFactoryOptions(options), 'options is not a valid SolidFactoryOptions object')
  // This adapter's buildRuntime can't accept `options` as-is: its signature is
  // `SolidFactoryOptions<TDefault, Props, Variants, TPreset> & TOptions`,
  // defaulting TPlugin itself and inferring a fresh TOptions — a specific
  // TPlugin instantiation isn't assignable to that default under
  // exactOptionalPropertyTypes (a known, separately-tracked plugin/styling
  // generic invariance; see the NormalizeFn bivariance note elsewhere in this
  // codebase). TPlugin is erased at runtime regardless, so no guard could
  // ever check this gap — it needs an assertion the same way buildRuntime's
  // TPlugin elision does in every other adapter. `as unknown as`, not the
  // original narrower `as`, since `C` (a single, formally independent type
  // parameter — see `@praxis-kit/react`'s identical comment) no longer
  // sufficiently overlaps with the reconstructed `SolidFactoryOptions<...>`
  // for a direct cast the way the old, separately-threaded generics did.
  const bundle = buildRuntime(
    options as unknown as SolidFactoryOptions<TDefault, Props, Variants, TPreset>,
  )
  const { onElement } = options

  const Component = (props: UnknownProps): SolidElement => {
    // Solid ref callbacks fire once, at element creation — a natural fit for "mount". They
    // don't fire again with null on unmount (unlike React), so cleanup is registered via
    // Solid's own onCleanup instead of a second ref invocation.
    const propsWithRef = onElement
      ? mergeProps(props, {
          get ref() {
            const consumerRef = (props as { ref?: unknown }).ref
            return (el: Element) => {
              if (typeof consumerRef === 'function') (consumerRef as (e: Element) => void)(el)
              // The real element's actual tag is only known at runtime; `onElement`'s parameter
              // type narrows that per-component via `TDefault`/`allowed`, which Solid's ref
              // contract itself can't express — see `FactoryOptions.onElement`.
              const cleanup = onElement(
                el as Parameters<NonNullable<typeof onElement>>[0],
                () => props as unknown as Readonly<Props>,
              )
              if (cleanup) onCleanup(cleanup)
            }
          },
        })
      : props

    return render({
      ...bundle,
      props: propsWithRef as KnownProps,
    })
  }

  applyDisplayName(Component, options.name)
  const assembled = finalizeComponent(
    Component,
    bundle.runtime.options.defaultTag,
    options.subComponents,
  )

  type G = PolymorphicGenerics<
    TDefault,
    MergeRecords<Props, ExtractPluginProps<TPlugin>>,
    Variants,
    TPreset
  >
  invariant(
    isPolymorphicComponent<G>(assembled),
    'Generated component failed to satisfy the PolymorphicComponent shape',
  )

  // MergeRecords is a conditional type. While these generics are still open, TypeScript cannot
  // prove that the assembled value satisfies the same conditional expression used by the
  // declared return type. Once the generics are instantiated at a call site, the conditional
  // simplifies correctly. The invariant above validates the runtime shape; this assertion
  // bridges the gap in the compiler's type reasoning. Also where `__contract`'s `C` is attached —
  // type-only, matching `__generics`: `assembled` never actually gains a `__contract` property at
  // runtime, only in the type this assertion claims.
  return assembled as unknown as MergeRecords<PolymorphicComponent<G, C>, TSubComponents>
}
