// adapters/preact/src/render.tsx
/**
 * Shared Preact rendering pipeline.
 *
 * Props are normalized into a `ResolvedRenderState`, optionally validated in development, then
 * dispatched to one of two render paths: Slot (`asChild`) or intrinsic element.
 */
import { h } from 'preact'
import type { Ref } from 'preact'
import type { Writable } from 'type-fest'
import type { ElementType, IntrinsicProps } from '@praxis-kit/core'
import { enforceAllowedAs } from '@praxis-kit/core'
import { isKnownAriaRole } from '@praxis-kit/core/primitive'
import { applyFilter } from '@praxis-kit/adapter-utils'
import type { SlotValidator } from './slot'
import { isSlottableElement } from './slot'
import type {
  SlotComponent,
  Runtime,
  KnownProps,
  RenderInput,
  ResolvedProps,
  ResolvedSlotRender,
  RenderDirectives,
  ResolvedRenderState,
  FilterPredicate,
  AnyVNode,
} from './types'

declare const process: { env: { NODE_ENV: string } }

function buildRenderState(
  tag: ElementType,
  directives: RenderDirectives,
  props: ResolvedProps,
  normalizedProps: ResolvedProps,
  className: string,
  children: unknown,
): ResolvedRenderState {
  const state: Writable<ResolvedRenderState> = {
    tag,
    directives,
    props,
    normalizedProps,
    className,
  }
  if (children !== undefined) state.children = children
  return state
}

/**
 * Resolves the component's render state.
 *
 * Applies tag resolution, prop normalization, class resolution, filtering, and render
 * directives, producing the canonical state consumed by every render path.
 */
function prepareRenderState(
  runtime: Runtime,
  props: KnownProps,
  filterProps: FilterPredicate,
): ResolvedRenderState {
  const { as, asChild, children, className, recipe, ...rest } = props
  const tag = runtime.resolveTag(as)
  if (runtime.options.allowedAs !== undefined && as !== undefined) {
    enforceAllowedAs(
      tag,
      runtime.options.allowedAs,
      runtime.options.diagnostics,
      runtime.options.displayName,
    )
  }
  const mergedProps = runtime.resolveProps(rest)
  const htmlNormalizers = runtime.options.htmlPropNormalizersFn?.(tag)
  const htmlNormalizedProps = htmlNormalizers?.length
    ? htmlNormalizers.reduce((acc, fn) => ({ ...acc, ...fn(acc) }), mergedProps)
    : mergedProps
  // HTML built-ins run first so enforcement.props normalizers (composed into normalizeFn, see
  // lib/primitive's composeNormalizers) and the caller's `normalize` option can see and override
  // their output — matching the order the hand-rolled adapter used to enforce.
  const normalizedProps = runtime.options.normalizeFn
    ? runtime.options.normalizeFn(htmlNormalizedProps)
    : htmlNormalizedProps
  const resolvedClass = runtime.resolveClasses(tag, normalizedProps, className, recipe)
  const filteredProps = applyFilter(normalizedProps, filterProps, runtime.options.variantKeys)
  const directives: RenderDirectives = {
    ...(as !== undefined && { as }),
    ...(asChild !== undefined && { asChild }),
  }
  return buildRenderState(tag, directives, filteredProps, normalizedProps, resolvedClass, children)
}

function warnDiscardedChildren(
  originalChildren: unknown,
  normalizedChildren: AnyVNode[],
  validator: SlotValidator,
): void {
  if (!Array.isArray(originalChildren)) return
  const discarded = originalChildren.length - normalizedChildren.length
  if (discarded > 0) validator.warnDiscardedChildren(discarded)
}

function isSingleElementArray(arr: AnyVNode[]): arr is [AnyVNode] {
  return arr.length === 1
}

function resolveSlotChildren(
  children: unknown,
  normalized: AnyVNode[],
  validator: SlotValidator,
): AnyVNode | AnyVNode[] | null {
  warnDiscardedChildren(children, normalized, validator)
  if (isSingleElementArray(normalized)) {
    return normalized[0]
  }
  // Slottable sibling pattern: [element, <Slottable>] — Slot handles the merge internally.
  if (normalized.length > 1 && normalized.some(isSlottableElement)) {
    return normalized
  }
  validator.assertSingleChild(normalized.length)
  // Non-throw modes: warned and fell through — render normally as a fallback.
  return null
}

function validateSlotDirectives(directives: RenderDirectives, validator: SlotValidator): boolean {
  const { as, asChild } = directives
  if (!asChild) return false
  if (as !== undefined) {
    validator.assertExclusive()
    // Non-throw modes: warned and fell through — render normally as a fallback.
    return false
  }
  return true
}

function resolveSlotRender(
  state: ResolvedRenderState,
  getNormalized: () => AnyVNode[],
  validator: SlotValidator,
): ResolvedSlotRender | null {
  if (!validateSlotDirectives(state.directives, validator)) return null
  const child = resolveSlotChildren(state.children, getNormalized(), validator)
  if (child === null) return null
  return { child }
}

function renderResolvedSlot(
  slotComponent: SlotComponent,
  state: ResolvedRenderState,
  slotRender: ResolvedSlotRender,
  ref: Ref<unknown> | null,
): AnyVNode {
  return h(slotComponent, {
    ...state.props,
    className: state.className,
    ref,
    children: slotRender.child,
  })
}

function tryRenderAsChild(
  state: ResolvedRenderState,
  ref: Ref<unknown> | null,
  slotComponent: SlotComponent,
  getNormalized: () => AnyVNode[],
  validator: SlotValidator,
): AnyVNode | null {
  const slotRender = resolveSlotRender(state, getNormalized, validator)
  if (slotRender === null) return null
  return renderResolvedSlot(slotComponent, state, slotRender, ref)
}

function buildElementProps(
  props: ResolvedProps,
  className: string,
  ref: Ref<unknown> | null,
  children: unknown,
): IntrinsicProps {
  const { role, ...rest } = props

  return {
    ...rest,
    className,
    ref,
    ...(children !== undefined && { children }),
    ...(isKnownAriaRole(role) && { role }),
  }
}

function renderIntrinsic(
  state: ResolvedRenderState,
  ref: Ref<unknown> | null,
  runtime: Runtime,
): AnyVNode {
  const elementProps = buildElementProps(state.props, state.className, ref, state.children)
  const domProps =
    typeof state.tag === 'string'
      ? runtime.resolveAria(state.tag, elementProps).props
      : elementProps
  return h(state.tag, domProps)
}

export function render<TProps extends KnownProps>({
  runtime,
  props,
  ref,
  slotComponent,
  normalizeChildren,
  filterProps,
  slotValidator,
  childrenEvaluator,
}: RenderInput<TProps>): AnyVNode {
  const state = prepareRenderState(runtime, props, filterProps)

  // Memoized on first access. Child normalization is shared between development
  // validation and Slot rendering so it runs at most once per render.
  let normalizedChildren: AnyVNode[] | undefined
  const getNormalizedChildren = (): AnyVNode[] =>
    (normalizedChildren ??= normalizeChildren(state.children))

  if (process.env.NODE_ENV !== 'production') {
    childrenEvaluator?.evaluate(getNormalizedChildren(), {
      tag: state.tag,
      props: state.normalizedProps,
    })
    runtime.options.htmlChildrenEvaluatorFn?.(state.tag)?.evaluate(getNormalizedChildren())
  }

  const slotResult = tryRenderAsChild(
    state,
    ref,
    slotComponent,
    getNormalizedChildren,
    slotValidator,
  )

  return slotResult ?? renderIntrinsic(state, ref, runtime)
}

// adapters/solid/src/render.tsx
import { applyFilter } from '@praxis-kit/adapter-utils'
import type { ElementType, IntrinsicProps } from '@praxis-kit/core'
import { enforceAllowedAs, isKnownAriaRole } from '@praxis-kit/core'
import { isString } from '@praxis-kit/primitive'
import { createEffect, createMemo, splitProps } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import type { SlotValidator } from './slot'
import type {
  KnownProps,
  RenderInput,
  ResolvedProps,
  Runtime,
  SolidElement,
  UnknownProps,
} from './types'

declare const process: { env: { NODE_ENV: string } }

// Keys consumed by the adapter — split from pass-through DOM props.
const SPLIT_KEYS = ['as', 'asChild', 'children', 'class', 'recipe', 'ref'] as const

function toChildArray(children: unknown): unknown[] {
  if (children === undefined || children === null) return []
  if (Array.isArray(children)) return children
  return [children]
}

function buildElementProps(
  props: ResolvedProps,
  classStr: string,
  ref: unknown,
  children: unknown,
): IntrinsicProps {
  const { role, ...rest } = props
  return {
    ...rest,
    class: classStr,
    ...(ref !== undefined && { ref }),
    ...(children !== undefined && { children }),
    ...(isKnownAriaRole(role) && { role }),
  }
}

// Slot props handed to the render function: fully resolved DOM props + class.
// ref is included so the render fn can forward it to the actual DOM element.
// children is excluded — the render fn decides its own children.
function buildSlotProps(props: ResolvedProps, classStr: string, ref: unknown): UnknownProps {
  const { role, ...rest } = props
  return {
    ...rest,
    class: classStr,
    ...(ref !== undefined && { ref }),
    ...(isKnownAriaRole(role) && { role }),
  }
}

function resolveTag(runtime: Runtime, as: unknown): ElementType {
  return runtime.resolveTag(as as ElementType | undefined)
}

function resolveDomProps(
  tag: ElementType,
  elementProps: IntrinsicProps,
  runtime: Runtime,
): UnknownProps {
  return isString(tag)
    ? (runtime.resolveAria(tag, elementProps).props as UnknownProps)
    : (elementProps as UnknownProps)
}

function tryRenderAsChild(
  known: KnownProps,
  filteredProps: () => ResolvedProps,
  resolvedClass: () => string,
  slotValidator: SlotValidator,
): SolidElement | null {
  if (!known.asChild) return null
  if (known.as !== undefined) {
    slotValidator.assertExclusive()
    return null
  }
  if (!slotValidator.assertRenderFn(known.children)) return null
  const renderFn = known.children as (p: UnknownProps) => SolidElement
  // createMemo tracks filteredProps() and resolvedClass() so slot props stay reactive.
  return createMemo(() =>
    renderFn(buildSlotProps(filteredProps(), resolvedClass(), known.ref)),
  ) as unknown as SolidElement
}

export function render<TProps extends KnownProps>({
  runtime,
  props,
  filterProps,
  slotValidator,
  childrenEvaluator,
}: RenderInput<TProps>): SolidElement {
  const [knownRaw, rest] = splitProps(props, SPLIT_KEYS)
  const known = knownRaw as unknown as KnownProps

  const tag = createMemo(() => resolveTag(runtime, known.as))
  const mergedProps = createMemo(() => runtime.resolveProps(rest as UnknownProps))
  const normalizedProps = createMemo(() => {
    const base = runtime.options.normalizeFn
      ? runtime.options.normalizeFn(mergedProps())
      : mergedProps()
    const htmlNormalizers = runtime.options.htmlPropNormalizersFn?.(tag())
    return htmlNormalizers?.length
      ? htmlNormalizers.reduce((acc, fn) => ({ ...acc, ...fn(acc) }), base)
      : base
  })
  const resolvedClass = createMemo(() =>
    runtime.resolveClasses(
      tag(),
      normalizedProps(),
      known.class as string | undefined,
      known.recipe as string | undefined,
    ),
  )
  const filteredProps = createMemo(() =>
    applyFilter(normalizedProps(), filterProps, runtime.options.variantKeys),
  )

  const { allowedAs } = runtime.options
  if (allowedAs !== undefined) {
    // createEffect so enforcement re-runs reactively when tag() changes.
    createEffect(() =>
      enforceAllowedAs(tag(), allowedAs, runtime.options.diagnostics, runtime.options.displayName),
    )
  }

  // createEffect so validation re-runs reactively when known.children changes.
  if (process.env.NODE_ENV !== 'production' && childrenEvaluator) {
    createEffect(() => childrenEvaluator.evaluate(toChildArray(known.children)))
  }

  if (process.env.NODE_ENV !== 'production') {
    createEffect(() =>
      runtime.options.htmlChildrenEvaluatorFn?.(tag())?.evaluate(toChildArray(known.children)),
    )
  }

  const slotResult = tryRenderAsChild(known, filteredProps, resolvedClass, slotValidator)
  if (slotResult !== null) return slotResult

  const domProps = createMemo(() => {
    const ep = buildElementProps(filteredProps(), resolvedClass(), known.ref, known.children)
    return resolveDomProps(tag(), ep, runtime)
  })

  // Dynamic dispatch — tag() and domProps() called directly in JSX so Solid's babel
  // transform wraps them in reactive getters, preserving fine-grained DOM updates.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return <Dynamic component={tag() as any} {...(domProps() as any)} />
}
