// examples/solid/src/tabs/Tabs.tsx
/**
 * Tabs — compound, stateful component for SolidJS built on praxis-kit.
 *
 * Solid's createSignal owns the active-tab state; createContext/useContext
 * propagates it down the tree. praxis-kit owns the contract layer.
 */
import { createSignal, Show } from 'solid-js'
import type { JSX, Component } from 'solid-js'
import { createContractComponent } from 'praxis-kit/solid'
import { TabsContext, useTabs } from './context'
import { tabId, panelId } from './utils'

// Solid requires capitalized identifiers for JSX component elements.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const toComponent = <T,>(c: T): Component<any> => c as Component<any>

// ── Trigger ───────────────────────────────────────────────────────────────────

const _TriggerContract = createContractComponent({
  tag: 'button' as const,
  name: 'TabsTrigger',
  defaults: { type: 'button' },
  styling: {
    base: 'px-3 py-2 text-sm font-medium border-b-2 border-transparent data-[state=active]:border-blue-600',
  },
})
const TriggerContract = toComponent(_TriggerContract)

export function Trigger(props: { value: string; children?: JSX.Element }): JSX.Element {
  const ctx = useTabs()
  const selected = () => ctx.value() === props.value
  return (
    <TriggerContract
      id={tabId(ctx.instanceId, props.value)}
      role="tab"
      aria-selected={selected()}
      aria-controls={panelId(ctx.instanceId, props.value)}
      data-state={selected() ? 'active' : 'inactive'}
      onClick={() => ctx.setValue(props.value)}
    >
      {props.children}
    </TriggerContract>
  )
}

// ── Indicator (presentational) ────────────────────────────────────────────────

const _IndicatorContract = createContractComponent({
  tag: 'span' as const,
  name: 'TabsIndicator',
  styling: { base: 'tabs-indicator block h-0.5 bg-blue-600 transition-all' },
})
const IndicatorContract = toComponent(_IndicatorContract)

export function Indicator(props: { class?: string }): JSX.Element {
  const ctx = useTabs()
  return (
    <IndicatorContract aria-hidden={true} data-active-value={ctx.value()} class={props.class} />
  )
}

// ── List (contract only — no state) ──────────────────────────────────────────

export const List = createContractComponent({
  tag: 'div' as const,
  name: 'TabsList',
  defaults: { role: 'tablist' },
  styling: { base: 'relative inline-flex gap-1 border-b border-gray-200' },
})

// ── Content ───────────────────────────────────────────────────────────────────

const _ContentContract = createContractComponent({
  tag: 'div' as const,
  name: 'TabsContent',
  defaults: { role: 'tabpanel' },
  styling: { base: 'py-4 text-sm' },
})
const ContentContract = toComponent(_ContentContract)

export function Content(props: { value: string; children?: JSX.Element }): JSX.Element {
  const ctx = useTabs()
  return (
    <Show when={ctx.value() === props.value}>
      <ContentContract
        id={panelId(ctx.instanceId, props.value)}
        aria-labelledby={tabId(ctx.instanceId, props.value)}
      >
        {props.children}
      </ContentContract>
    </Show>
  )
}

// ── Root ──────────────────────────────────────────────────────────────────────

const _RootContract = createContractComponent({
  tag: 'div' as const,
  name: 'TabsRoot',
  styling: { base: 'flex flex-col' },
})
const RootContract = toComponent(_RootContract)

let _id = 0

export function Root(props: {
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  children?: JSX.Element
}): JSX.Element {
  const instanceId = `tabs-${++_id}`
  const [uncontrolled, setUncontrolled] = createSignal(props.defaultValue ?? '')

  const value = () => props.value ?? uncontrolled()

  const setValue = (next: string) => {
    if (props.value === undefined) setUncontrolled(next)
    props.onValueChange?.(next)
  }

  return (
    <TabsContext.Provider value={{ instanceId, value, setValue }}>
      <RootContract>{props.children}</RootContract>
    </TabsContext.Provider>
  )
}

// ── Namespace ─────────────────────────────────────────────────────────────────
export const Tabs = { Root, List, Trigger, Content, Indicator }

// examples/preact/src/tabs/Tabs.tsx
/**
 * Tabs — compound, stateful component for Preact built on praxis-kit.
 *
 * Mirrors the React Tabs example. Preact's createContext/useContext (from
 * preact/compat) owns active-tab state; praxis-kit owns the contract layer.
 */
import { h } from 'preact'
import type { ComponentChildren } from 'preact'
import { useState } from 'preact/hooks'
import { createContractComponent } from '@praxis-kit/preact'
import { TabsContext, useTabs } from './context'
import { isType, tabId, panelId } from './utils'

// ── Trigger ───────────────────────────────────────────────────────────────────

const TriggerContract = createContractComponent({
  tag: 'button' as const,
  name: 'TabsTrigger',
  defaults: { type: 'button' },
  styling: {
    base: 'px-3 py-2 text-sm font-medium border-b-2 border-transparent data-[state=active]:border-blue-600',
  },
})

function Trigger({ value, children }: { value: string; children?: ComponentChildren }) {
  const ctx = useTabs()
  const selected = ctx.value === value
  return h(
    TriggerContract as never,
    {
      id: tabId(ctx.instanceId, value),
      role: 'tab',
      'aria-selected': selected,
      'aria-controls': panelId(ctx.instanceId, value),
      'data-state': selected ? 'active' : 'inactive',
      onClick: () => ctx.setValue(value),
    },
    children,
  )
}

// ── Indicator (presentational) ────────────────────────────────────────────────

const IndicatorContract = createContractComponent({
  tag: 'span' as const,
  name: 'TabsIndicator',
  styling: { base: 'tabs-indicator block h-0.5 bg-blue-600 transition-all' },
})

function Indicator({ class: cls }: { class?: string }) {
  const ctx = useTabs()
  return h(IndicatorContract as never, {
    'aria-hidden': true,
    'data-active-value': ctx.value,
    ...(cls !== undefined && { class: cls }),
  })
}

// ── List (contract only — no state) ──────────────────────────────────────────

const List = createContractComponent({
  tag: 'div' as const,
  name: 'TabsList',
  defaults: { role: 'tablist' },
  styling: { base: 'relative inline-flex gap-1 border-b border-gray-200' },
  enforcement: {
    strict: 'warn',
    children: [
      { name: 'Tabs.Trigger', match: isType(Trigger), cardinality: { min: 1 } },
      { name: 'Tabs.Indicator', match: isType(Indicator), cardinality: { max: 1 } },
    ],
  },
})

// ── Content ───────────────────────────────────────────────────────────────────

const ContentContract = createContractComponent({
  tag: 'div' as const,
  name: 'TabsContent',
  defaults: { role: 'tabpanel' },
  styling: { base: 'py-4 text-sm' },
})

function Content({ value, children }: { value: string; children?: ComponentChildren }) {
  const ctx = useTabs()
  if (ctx.value !== value) return null
  return h(
    ContentContract as never,
    {
      id: panelId(ctx.instanceId, value),
      'aria-labelledby': tabId(ctx.instanceId, value),
    },
    children,
  )
}

// ── Root ──────────────────────────────────────────────────────────────────────

const RootContract = createContractComponent({
  tag: 'div' as const,
  name: 'TabsRoot',
  styling: { base: 'flex flex-col' },
  enforcement: {
    strict: 'warn',
    children: [
      { name: 'Tabs.List', match: isType(List), cardinality: { min: 1, max: 1 } },
      { name: 'Tabs.Content', match: isType(Content), cardinality: { min: 1 } },
    ],
  },
})

let _id = 0

function Root({
  value: controlledValue,
  defaultValue,
  onValueChange,
  children,
}: {
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  children?: ComponentChildren
}) {
  const instanceId = `tabs-${++_id}`
  const [uncontrolled, setUncontrolled] = useState(defaultValue ?? '')

  const value = controlledValue ?? uncontrolled

  const setValue = (next: string) => {
    if (controlledValue === undefined) setUncontrolled(next)
    onValueChange?.(next)
  }

  return h(
    TabsContext.Provider,
    { value: { instanceId, value, setValue } },
    h(RootContract as never, {}, children),
  )
}

// ── Namespace ─────────────────────────────────────────────────────────────────
export const Tabs = { Root, List, Trigger, Content, Indicator }
