// packages/solid/src/types/polymorphic-props.ts
import type { JSX } from 'solid-js'
import type { OmitIndexSignature, Simplify } from 'type-fest'
import type {
  ClassName,
  DefaultOf,
  ElementType,
  IntrinsicTag,
  PolymorphicGenerics,
  PresetOf,
  PropsOf,
  VariantProps,
  VariantsOf,
} from '@polymorphic-ui/core'
import type { SlotRenderFn, UnknownProps } from './primitives'

export type ElementRef<T extends ElementType> = T extends IntrinsicTag
  ? HTMLElementTagNameMap[T]
  : unknown

type IntrinsicJSXProps<T extends ElementType> = T extends IntrinsicTag
  ? JSX.IntrinsicElements[T]
  : UnknownProps

type ControlProps<G extends PolymorphicGenerics, TAs extends ElementType> = PropsOf<G> &
  // OmitIndexSignature strips the [k: string]: string|undefined leak from
  // VariantProps<VariantMap> (the default when no variants are defined).
  // Named variant keys (size, intent, …) are literal and survive the strip.
  OmitIndexSignature<VariantProps<VariantsOf<G>>> & {
    as?: TAs
    class?: ClassName
    variantKey?: keyof PresetOf<G>
    ref?: (el: ElementRef<TAs>) => void
  }

type SharedProps<G extends PolymorphicGenerics, TAs extends ElementType> = Omit<
  IntrinsicJSXProps<TAs>,
  keyof ControlProps<G, TAs> | 'children' | 'ref'
> &
  ControlProps<G, TAs>

// When asChild is true, intrinsic DOM props (type, href, …) are not required — the
// render function owns the element and its required attributes. PropsOf<G> (component
// defaults) is made Partial because those values are filled by the runtime; callers
// should not be forced to re-supply them. ref is typed loosely because the actual
// element type depends on what the render function produces.
type AsChildProps<G extends PolymorphicGenerics> = Partial<PropsOf<G>> &
  OmitIndexSignature<VariantProps<VariantsOf<G>>> & {
    as?: never
    asChild: true
    children: SlotRenderFn
    class?: ClassName
    variantKey?: keyof PresetOf<G>
    ref?: unknown
  }

export type PolymorphicProps<
  G extends PolymorphicGenerics,
  TAs extends ElementType = DefaultOf<G>,
> = Simplify<(SharedProps<G, TAs> & { asChild?: false; children?: unknown }) | AsChildProps<G>>

export type PolymorphicComponent<G extends PolymorphicGenerics> = {
  <TAs extends ElementType = DefaultOf<G>>(props: PolymorphicProps<G, TAs>): JSX.Element
  displayName?: string
}

// packages/react/src/shared/polymorphic-props.ts
import type { Merge } from 'type-fest'
import type { JSX, ReactElement, Ref } from 'react'
import type {
  AnyRecord,
  ClassName,
  ElementType,
  IntrinsicTag,
  VariantMap,
  VariantProps,
} from '@polymorphic-ui/core'

/** Maps a core ElementType to its DOM instance type for ref inference. */
export type ElementRef<T extends ElementType> = T extends IntrinsicTag
  ? HTMLElementTagNameMap[T]
  : unknown

/** React JSX intrinsic props for a given element type. */
type IntrinsicJSXProps<T extends ElementType> = T extends IntrinsicTag
  ? JSX.IntrinsicElements[T]
  : AnyRecord

/**
 * The full prop surface for a polymorphic component rendered as `TAs`.
 *
 * HTML attributes are inferred from `TAs` (the resolved `as` prop), merged with
 * component-defined `Props` and `Variants`. Control props are applied last and
 * cannot be shadowed by intrinsic attributes or custom props.
 *
 * Merge produces a flat mapped type (Source wins on key conflicts), so the IDE
 * shows a clean resolved object rather than a nested Omit/intersection chain.
 */
export type PolymorphicProps<
  TDefault extends ElementType,
  Props extends AnyRecord,
  Variants extends Readonly<VariantMap>,
  TPreset extends Record<string, Partial<VariantProps<Variants>>>,
  TAs extends ElementType = TDefault,
> = Merge<
  IntrinsicJSXProps<TAs>,
  Props &
    VariantProps<Variants> & {
      as?: TAs
      asChild?: boolean
      className?: ClassName
      variantKey?: keyof TPreset
      ref?: Ref<ElementRef<TAs>>
    }
>

/**
 * A polymorphic component that infers HTML attributes and ref type from the `as` prop.
 *
 * When callers write `<MyComp as="button" ref={...} />`, TypeScript infers
 * `TAs = "button"` and types `ref` as `Ref<HTMLButtonElement>` automatically.
 */
export type PolymorphicComponent<
  TDefault extends ElementType,
  Props extends AnyRecord,
  Variants extends Readonly<VariantMap>,
  TPreset extends Record<string, Partial<VariantProps<Variants>>>,
> = {
  <TAs extends ElementType = TDefault>(
    props: PolymorphicProps<TDefault, Props, Variants, TPreset, TAs>,
  ): ReactElement
  displayName?: string
}
