// packages/solid/src/render.tsx
import { createMemo, splitProps } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import type { ElementType, IntrinsicProps } from '@polymorphic-ui/core'
import { isKnownAriaRole } from '@polymorphic-ui/core'
import type { FilterPredicate, ResolvedProps, SolidElement, UnknownProps } from './types/primitives'
import type { KnownProps } from './types/props'
import type { RenderInput } from './types/render'
import type { Runtime } from './types/runtime'
import type { SlotValidator } from './slot/slot-validator'

// Keys consumed by the adapter — split from pass-through DOM props.
const SPLIT_KEYS = ['as', 'asChild', 'children', 'class', 'variantKey', 'ref'] as const

function applyFilter<T extends ResolvedProps>(
  props: T,
  filterProps: FilterPredicate,
  variantKeys: ReadonlySet<string>,
): T {
  const out = {} as T
  for (const [k, v] of Object.entries(props)) {
    if (!filterProps(k, variantKeys)) (out as UnknownProps)[k] = v
  }
  return out
}

function toChildArray(children: unknown): unknown[] {
  if (children === undefined || children === null) return []
  if (Array.isArray(children)) return children
  return [children]
}

function buildElementProps(
  props: ResolvedProps,
  classStr: string,
  ref: unknown,
  children: unknown,
): IntrinsicProps {
  const { role, ...rest } = props
  return {
    ...rest,
    class: classStr,
    ...(ref !== undefined && { ref }),
    ...(children !== undefined && { children }),
    ...(isKnownAriaRole(role) && { role }),
  }
}

// Slot props handed to the render function: fully resolved DOM props + class.
// ref is included so the render fn can forward it to the actual DOM element.
// children is excluded — the render fn decides its own children.
function buildSlotProps(props: ResolvedProps, classStr: string, ref: unknown): UnknownProps {
  const { role, ...rest } = props
  return {
    ...rest,
    class: classStr,
    ...(ref !== undefined && { ref }),
    ...(isKnownAriaRole(role) && { role }),
  }
}

function resolveTag(runtime: Runtime, as: unknown): ElementType {
  return runtime.resolveTag(as as ElementType | undefined)
}

function resolveDomProps(
  tag: ElementType,
  elementProps: IntrinsicProps,
  runtime: Runtime,
): UnknownProps {
  return typeof tag === 'string'
    ? (runtime.resolveAria(tag, elementProps).props as UnknownProps)
    : (elementProps as UnknownProps)
}

function tryRenderAsChild(
  known: KnownProps,
  filteredProps: () => ResolvedProps,
  resolvedClass: () => string,
  slotValidator: SlotValidator,
): SolidElement | null {
  if (!known.asChild) return null
  if (known.as !== undefined) {
    slotValidator.assertExclusive()
    return null
  }
  if (!slotValidator.assertRenderFn(known.children)) return null
  const renderFn = known.children as (p: UnknownProps) => SolidElement
  // createMemo tracks filteredProps() and resolvedClass() so slot props stay reactive.
  return createMemo(() =>
    renderFn(buildSlotProps(filteredProps(), resolvedClass(), known.ref)),
  ) as unknown as SolidElement
}

export function render<TProps extends KnownProps>({
  runtime,
  props,
  filterProps,
  slotValidator,
  childrenEvaluator,
}: RenderInput<TProps>): SolidElement {
  const [knownRaw, rest] = splitProps(props, SPLIT_KEYS)
  const known = knownRaw as unknown as KnownProps

  const tag = createMemo(() => resolveTag(runtime, known.as))
  const mergedProps = createMemo(() => runtime.resolveProps(rest as UnknownProps))
  const resolvedClass = createMemo(() =>
    runtime.resolveClasses(
      tag(),
      mergedProps(),
      known.class as string | undefined,
      known.variantKey as string | undefined,
    ),
  )
  const filteredProps = createMemo(() =>
    applyFilter(mergedProps(), filterProps, runtime.options.variantKeys),
  )

  childrenEvaluator?.evaluate(toChildArray(known.children))

  const slotResult = tryRenderAsChild(known, filteredProps, resolvedClass, slotValidator)
  if (slotResult !== null) return slotResult

  const domProps = createMemo(() => {
    const ep = buildElementProps(filteredProps(), resolvedClass(), known.ref, known.children)
    return resolveDomProps(tag(), ep, runtime)
  })

  // Dynamic dispatch — tag() and domProps() called directly in JSX so Solid's babel
  // transform wraps them in reactive getters, preserving fine-grained DOM updates.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return <Dynamic component={tag() as any} {...(domProps() as any)} />
}

// packages/react/src/shared/render.ts
import { createElement } from 'react'
import { jsx } from 'react/jsx-runtime'
import type { ReactElement, Ref } from 'react'
import type { AriaPolicyEngine, ElementType, IntrinsicProps } from '@polymorphic-ui/core'
import { isKnownAriaRole } from '@polymorphic-ui/core'
import type { SlotValidator } from './slot'
import { isSlottableElement } from './slot'
import type {
  UnknownProps,
  SlotComponent,
  Runtime,
  KnownProps,
  RenderInput,
  NormalizeChildren,
  ResolvedProps,
  ResolvedSlotRender,
  RenderDirectives,
  FilterPredicate,
  ResolvedRenderState,
} from './types'

function applyFilter<T extends ResolvedProps>(
  props: T,
  filterProps: FilterPredicate,
  variantKeys: ReadonlySet<string>,
): T {
  const out = {} as T
  for (const [k, v] of Object.entries(props)) {
    if (!filterProps(k, variantKeys)) (out as UnknownProps)[k] = v
  }
  return out
}

function buildDirectives(
  as: ElementType | undefined,
  asChild: boolean | undefined,
): RenderDirectives {
  return {
    ...(as !== undefined && { as }),
    ...(asChild !== undefined && { asChild }),
  }
}

function buildRenderState(
  tag: ElementType,
  directives: RenderDirectives,
  props: ResolvedProps,
  className: string,
  children: unknown,
): ResolvedRenderState {
  const state: {
    tag: ElementType
    directives: RenderDirectives
    props: ResolvedProps
    className: string
    children?: unknown
  } = { tag, directives, props, className }
  if (children !== undefined) state.children = children
  return state
}

function resolveRenderState(
  runtime: Runtime,
  props: KnownProps,
  filterProps: FilterPredicate,
): ResolvedRenderState {
  const { as, asChild, children, className, variantKey, ...rest } = props
  const tag = runtime.resolveTag(as)
  const mergedProps = runtime.resolveProps(rest)
  const resolvedClass = runtime.resolveClasses(tag, mergedProps, className, variantKey)
  const filteredProps = applyFilter(mergedProps, filterProps, runtime.options.variantKeys)
  return buildRenderState(tag, buildDirectives(as, asChild), filteredProps, resolvedClass, children)
}

function warnDiscardedChildren(
  originalChildren: unknown,
  normalizedChildren: ReactElement[],
  validator: SlotValidator,
): void {
  if (!Array.isArray(originalChildren)) return
  const discarded = originalChildren.length - normalizedChildren.length
  if (discarded > 0) validator.warnDiscardedChildren(discarded)
}

function isSingleElementArray(arr: ReactElement[]): arr is [ReactElement] {
  return arr.length === 1
}

function resolveSlotChildren(
  children: unknown,
  normalizeChildren: NormalizeChildren,
  validator: SlotValidator,
): ReactElement | ReactElement[] | null {
  const normalized = normalizeChildren(children)
  warnDiscardedChildren(children, normalized, validator)
  if (isSingleElementArray(normalized)) {
    return normalized[0]
  }
  // Slottable sibling pattern: [element, <Slottable>] — Slot handles the merge internally.
  if (normalized.length > 1 && normalized.some(isSlottableElement)) {
    return normalized
  }
  validator.assertSingleChild(normalized.length)
  // Non-throw modes: warned and fell through — render normally as a fallback.
  return null
}

function validateSlotDirectives(directives: RenderDirectives, validator: SlotValidator): boolean {
  const { as, asChild } = directives
  if (!asChild) return false
  if (as !== undefined) {
    validator.assertExclusive()
    // Non-throw modes: warned and fell through — render normally as a fallback.
    return false
  }
  return true
}

function resolveSlotRender(
  state: ResolvedRenderState,
  normalizeChildren: NormalizeChildren,
  validator: SlotValidator,
): ResolvedSlotRender | null {
  if (!validateSlotDirectives(state.directives, validator)) return null
  const child = resolveSlotChildren(state.children, normalizeChildren, validator)
  if (child === null) return null
  return { child }
}

function renderResolvedSlot(
  slotComponent: SlotComponent,
  state: ResolvedRenderState,
  resolved: ResolvedSlotRender,
  ref: Ref<unknown> | null,
): ReactElement {
  return jsx(slotComponent, {
    ...state.props,
    className: state.className,
    ref,
    children: resolved.child,
  })
}

function tryRenderAsChild(
  state: ResolvedRenderState,
  ref: Ref<unknown> | null,
  slotComponent: SlotComponent,
  normalizeChildren: NormalizeChildren,
  validator: SlotValidator,
): ReactElement | null {
  const resolved = resolveSlotRender(state, normalizeChildren, validator)
  if (resolved === null) return null
  return renderResolvedSlot(slotComponent, state, resolved, ref)
}

function buildElementProps(
  props: ResolvedProps,
  className: string,
  ref: Ref<unknown> | null,
  children: unknown,
): IntrinsicProps {
  const { role, ...rest } = props

  return {
    ...rest,
    className,
    ref,
    ...(children !== undefined && { children }),
    ...(isKnownAriaRole(role) && { role }),
  }
}

function renderIntrinsic(
  state: ResolvedRenderState,
  ref: Ref<unknown> | null,
  ariaEngine: AriaPolicyEngine,
): ReactElement {
  const elementProps = buildElementProps(state.props, state.className, ref, state.children)
  const domProps =
    typeof state.tag === 'string'
      ? ariaEngine.validate(state.tag, elementProps).props
      : elementProps
  return createElement(state.tag, domProps)
}

export function render<TProps extends KnownProps>({
  runtime,
  props,
  ref,
  slotComponent,
  normalizeChildren,
  filterProps,
  slotValidator,
  ariaEngine,
  childrenEvaluator,
}: RenderInput<TProps>): ReactElement {
  const state = resolveRenderState(runtime, props, filterProps)

  childrenEvaluator?.evaluate(normalizeChildren(state.children))

  const slotResult = tryRenderAsChild(state, ref, slotComponent, normalizeChildren, slotValidator)

  return slotResult ?? renderIntrinsic(state, ref, ariaEngine)
}
